import React from "react";
import "./termsStyles.scss";

const Register = () => {

  return (
    <div id="terms">
      <div className='contentTerms'>
        <h1>TÉRMINOS Y CONDICIONES</h1>

          <p>Exercitation ipsum minim quis veniam nostrud culpa dolore ea aute duis aute cillum esse cupidatat. Ullamco ea excepteur ullamco duis minim occaecat pariatur tempor sint laborum elit qui dolore minim. In irure commodo eiusmod excepteur.</p>
          <p>Nostrud eu commodo tempor in labore exercitation qui commodo. Dolor qui amet sint ea aliquip ex voluptate. Eiusmod esse deserunt proident quis. Incididunt nisi enim velit mollit reprehenderit ad aute fugiat exercitation ad commodo cupidatat. Eu adipisicing sit irure minim enim duis laboris labore irure qui. Nostrud nostrud sit sit fugiat et ut et magna dolor amet sit magna qui. Anim fugiat eiusmod nulla sunt eu laborum mollit eu aute.</p>
          <p>Enim minim labore qui ut nulla irure commodo consequat anim quis est consequat dolore. Labore reprehenderit aute proident nisi sit cupidatat excepteur ullamco. Culpa occaecat dolore in quis eu velit exercitation ex elit laborum tempor irure adipisicing in. Dolor non elit amet do culpa magna cillum magna anim laboris. Consectetur ut id esse in laboris excepteur ex. Consequat nisi magna excepteur reprehenderit. Minim ea nulla esse adipisicing ad cillum.</p>
          <p>Consectetur cillum irure excepteur elit duis velit magna occaecat non nostrud officia fugiat. Magna deserunt dolore voluptate dolore dolor adipisicing. Magna fugiat cillum consequat sint duis incididunt cillum est ullamco deserunt dolore. Cillum deserunt quis duis enim aliquip pariatur cillum.</p>
          <p>Officia cillum officia non mollit culpa non enim. Velit adipisicing ullamco nostrud quis esse non aliquip ullamco. Nostrud commodo ex sit aliqua officia non esse cupidatat nulla magna cillum eiusmod in. Est non ad tempor ea ullamco dolor ex eiusmod laboris adipisicing Lorem eiusmod. Occaecat proident quis nisi ea ipsum et ex nisi commodo aute cillum est ad magna. Et qui consequat tempor officia cillum occaecat amet dolor labore adipisicing anim occaecat.</p>
          <p>Laboris nostrud veniam sunt dolore sunt labore. Qui do sint laborum labore duis excepteur labore laboris esse. Ut laborum sunt ea anim duis dolor quis fugiat qui consectetur. Dolor magna eiusmod exercitation incididunt labore do consequat ipsum adipisicing reprehenderit.</p>
          <p>Id non officia Lorem enim cillum pariatur. Lorem id officia occaecat ut non proident enim quis non veniam. Ut sit nostrud et consectetur velit sunt ea id laboris nostrud.</p>
          <p>Nulla eu veniam magna id ad ipsum. Ad laborum voluptate fugiat excepteur aliqua quis quis irure anim et et eiusmod aute. Est aliqua sunt ea duis fugiat amet dolore pariatur velit amet. Tempor exercitation irure tempor labore officia. In nisi nisi aliquip laborum sunt amet. Nulla amet incididunt deserunt excepteur exercitation. Voluptate dolor reprehenderit fugiat incididunt in aliqua occaecat.</p>
          <p>Exercitation ipsum minim quis veniam nostrud culpa dolore ea aute duis aute cillum esse cupidatat. Ullamco ea excepteur ullamco duis minim occaecat pariatur tempor sint laborum elit qui dolore minim. In irure commodo eiusmod excepteur.</p>
          <p>Nostrud eu commodo tempor in labore exercitation qui commodo. Dolor qui amet sint ea aliquip ex voluptate. Eiusmod esse deserunt proident quis. Incididunt nisi enim velit mollit reprehenderit ad aute fugiat exercitation ad commodo cupidatat. Eu adipisicing sit irure minim enim duis laboris labore irure qui. Nostrud nostrud sit sit fugiat et ut et magna dolor amet sit magna qui. Anim fugiat eiusmod nulla sunt eu laborum mollit eu aute.</p>
          <p>Enim minim labore qui ut nulla irure commodo consequat anim quis est consequat dolore. Labore reprehenderit aute proident nisi sit cupidatat excepteur ullamco. Culpa occaecat dolore in quis eu velit exercitation ex elit laborum tempor irure adipisicing in. Dolor non elit amet do culpa magna cillum magna anim laboris. Consectetur ut id esse in laboris excepteur ex. Consequat nisi magna excepteur reprehenderit. Minim ea nulla esse adipisicing ad cillum.</p>
          <p>Consectetur cillum irure excepteur elit duis velit magna occaecat non nostrud officia fugiat. Magna deserunt dolore voluptate dolore dolor adipisicing. Magna fugiat cillum consequat sint duis incididunt cillum est ullamco deserunt dolore. Cillum deserunt quis duis enim aliquip pariatur cillum.</p>
          <p>Officia cillum officia non mollit culpa non enim. Velit adipisicing ullamco nostrud quis esse non aliquip ullamco. Nostrud commodo ex sit aliqua officia non esse cupidatat nulla magna cillum eiusmod in. Est non ad tempor ea ullamco dolor ex eiusmod laboris adipisicing Lorem eiusmod. Occaecat proident quis nisi ea ipsum et ex nisi commodo aute cillum est ad magna. Et qui consequat tempor officia cillum occaecat amet dolor labore adipisicing anim occaecat.</p>
          <p>Laboris nostrud veniam sunt dolore sunt labore. Qui do sint laborum labore duis excepteur labore laboris esse. Ut laborum sunt ea anim duis dolor quis fugiat qui consectetur. Dolor magna eiusmod exercitation incididunt labore do consequat ipsum adipisicing reprehenderit.</p>
          <p>Id non officia Lorem enim cillum pariatur. Lorem id officia occaecat ut non proident enim quis non veniam. Ut sit nostrud et consectetur velit sunt ea id laboris nostrud.</p>
          <p>Nulla eu veniam magna id ad ipsum. Ad laborum voluptate fugiat excepteur aliqua quis quis irure anim et et eiusmod aute. Est aliqua sunt ea duis fugiat amet dolore pariatur velit amet. Tempor exercitation irure tempor labore officia. In nisi nisi aliquip laborum sunt amet. Nulla amet incididunt deserunt excepteur exercitation. Voluptate dolor reprehenderit fugiat incididunt in aliqua occaecat.</p>
          <p>Exercitation ipsum minim quis veniam nostrud culpa dolore ea aute duis aute cillum esse cupidatat. Ullamco ea excepteur ullamco duis minim occaecat pariatur tempor sint laborum elit qui dolore minim. In irure commodo eiusmod excepteur.</p>
          <p>Nostrud eu commodo tempor in labore exercitation qui commodo. Dolor qui amet sint ea aliquip ex voluptate. Eiusmod esse deserunt proident quis. Incididunt nisi enim velit mollit reprehenderit ad aute fugiat exercitation ad commodo cupidatat. Eu adipisicing sit irure minim enim duis laboris labore irure qui. Nostrud nostrud sit sit fugiat et ut et magna dolor amet sit magna qui. Anim fugiat eiusmod nulla sunt eu laborum mollit eu aute.</p>
          <p>Enim minim labore qui ut nulla irure commodo consequat anim quis est consequat dolore. Labore reprehenderit aute proident nisi sit cupidatat excepteur ullamco. Culpa occaecat dolore in quis eu velit exercitation ex elit laborum tempor irure adipisicing in. Dolor non elit amet do culpa magna cillum magna anim laboris. Consectetur ut id esse in laboris excepteur ex. Consequat nisi magna excepteur reprehenderit. Minim ea nulla esse adipisicing ad cillum.</p>
          <p>Consectetur cillum irure excepteur elit duis velit magna occaecat non nostrud officia fugiat. Magna deserunt dolore voluptate dolore dolor adipisicing. Magna fugiat cillum consequat sint duis incididunt cillum est ullamco deserunt dolore. Cillum deserunt quis duis enim aliquip pariatur cillum.</p>
          <p>Officia cillum officia non mollit culpa non enim. Velit adipisicing ullamco nostrud quis esse non aliquip ullamco. Nostrud commodo ex sit aliqua officia non esse cupidatat nulla magna cillum eiusmod in. Est non ad tempor ea ullamco dolor ex eiusmod laboris adipisicing Lorem eiusmod. Occaecat proident quis nisi ea ipsum et ex nisi commodo aute cillum est ad magna. Et qui consequat tempor officia cillum occaecat amet dolor labore adipisicing anim occaecat.</p>
          <p>Laboris nostrud veniam sunt dolore sunt labore. Qui do sint laborum labore duis excepteur labore laboris esse. Ut laborum sunt ea anim duis dolor quis fugiat qui consectetur. Dolor magna eiusmod exercitation incididunt labore do consequat ipsum adipisicing reprehenderit.</p>
          <p>Id non officia Lorem enim cillum pariatur. Lorem id officia occaecat ut non proident enim quis non veniam. Ut sit nostrud et consectetur velit sunt ea id laboris nostrud.</p>
          <p>Nulla eu veniam magna id ad ipsum. Ad laborum voluptate fugiat excepteur aliqua quis quis irure anim et et eiusmod aute. Est aliqua sunt ea duis fugiat amet dolore pariatur velit amet. Tempor exercitation irure tempor labore officia. In nisi nisi aliquip laborum sunt amet. Nulla amet incididunt deserunt excepteur exercitation. Voluptate dolor reprehenderit fugiat incididunt in aliqua occaecat.</p>
      </div>
    </div>
  );
};

export default Register;
